### ISSUE TITLE
`test-splitter --version` fails

### ISSUE THREAD

**Issue by sj26** [buildkite/test-splitter#106]
I tried running `test-splitter --version` to be sure I had installed it right, but it outputs a bunch of errors, no version information, and exits non-zero:

<img width="501" alt="image" src="https://github.com/buildkite/test-splitter/assets/14028/b27a217d-46e1-46e1-99a4-f18f12b77c84">

**Comment by wooly** [comment]
Thanks for raising! I’ve got a local branch to fix this, will get it pushed soon!
