### ISSUE TITLE
Exclude pattern parameter doesn't seem to work as documented

### ISSUE THREAD

**Issue by TJC** [buildkite/test-splitter#52]
Hi,
I'm trying to use the test-splitter on a project that requires some unit tests to run on a different set of agents.

These use Ruby Rspec, and I could potentially use either rspec tags, or simple file paths, to pick them out. I'm trying to use the `BUILDKITE_SPLITTER_TEST_FILE_EXCLUDE_PATTERN` parameter to achieve this, but it doesn't seem to be working for me.

For example, I am trying this command, but finding it still runs rspecs from within that directory.

`BUILDKITE_SPLITTER_TEST_FILE_EXCLUDE_PATTERN=spec/acceptance/** test-splitter`

Is this the right way to do this?

Do I need to change the include pattern to be very minimal, perhaps?

**Comment by TJC** [comment]
Update: I think we're running an older version of the test-splitter. I'll update and re-test, and re-open this issue if needs be.

**Comment by amybiyuliu** [comment]
Hi @TJC I'm Amy from Buildkite 👋 Thanks for raising the issue, and please let us know if you have more questions setting up the test splitter!

**Comment by niceking** [comment]
Hey @TJC! Perhaps bumping the version of the Test Splitter will help 😂 If not, it might be how you're specifying your exclude pattern? We expect the exclude pattern to take the form of a file glob, not a directory path as you're probably used to doing with Rspec! 

If you want to exclude all the acceptance specs, you'll need to do something like:
`BUILDKITE_SPLITTER_TEST_FILE_EXCLUDE_PATTERN=spec/acceptance/**/*_spec.rb`

**Comment by TJC** [comment]
@niceking You mentioned that you expect the pattern to take the form of a file glob, not a directory. However the documentation actually states otherwise:

> Optional, glob pattern to use for excluding test files or directory.

**Comment by niceking** [comment]
Thanks for the feedback @TJC, I've made a PR for this here: https://github.com/buildkite/test-splitter/pull/54

Does that help clarify what we expect? Also, you might have already seen this, but we also link out to the glob library that we use to interpret the given globs: 
<img width="833" alt="Screenshot 2024-05-06 at 1 26 18 PM" src="https://github.com/buildkite/test-splitter/assets/4241125/ca7a6d3a-a6b3-4c32-95a4-8edb5fc0bf42">

Let me me know here or on the PR if you think the wording could be clearer 😄
